// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxWPlJYZK4wRJkUZcLz3zOP3El1vI1Utw',
    appId: '1:972001079189:web:c46a77e7b8c6fa8782509c',
    messagingSenderId: '972001079189',
    projectId: 'task-treck-75d7c',
    authDomain: 'task-treck-75d7c.firebaseapp.com',
    storageBucket: 'task-treck-75d7c.appspot.com',
    measurementId: 'G-T0QJJQ6V1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtwYBd1NOWPDSeU3FQE_bcy2CqpHXxebU',
    appId: '1:972001079189:android:8612ef41c96d281182509c',
    messagingSenderId: '972001079189',
    projectId: 'task-treck-75d7c',
    storageBucket: 'task-treck-75d7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1keNVGz989_-BfbGAnD0YKJzG7H_c1zk',
    appId: '1:972001079189:ios:fd6d9e5f5a78d44382509c',
    messagingSenderId: '972001079189',
    projectId: 'task-treck-75d7c',
    storageBucket: 'task-treck-75d7c.appspot.com',
    iosBundleId: 'com.example.machineTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1keNVGz989_-BfbGAnD0YKJzG7H_c1zk',
    appId: '1:972001079189:ios:fd6d9e5f5a78d44382509c',
    messagingSenderId: '972001079189',
    projectId: 'task-treck-75d7c',
    storageBucket: 'task-treck-75d7c.appspot.com',
    iosBundleId: 'com.example.machineTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxWPlJYZK4wRJkUZcLz3zOP3El1vI1Utw',
    appId: '1:972001079189:web:8a92973e09d23e0482509c',
    messagingSenderId: '972001079189',
    projectId: 'task-treck-75d7c',
    authDomain: 'task-treck-75d7c.firebaseapp.com',
    storageBucket: 'task-treck-75d7c.appspot.com',
    measurementId: 'G-YG4H45VJR3',
  );
}
